name: Release and Publish
on:
  release:
    types:
      - published

permissions:
  contents: write
  actions: write
  checks: write

jobs:
  Test:
    uses: ./.github/workflows/action-test.yaml

  Strip_Version:
    runs-on: ubuntu-latest
    steps:
      - name: Strip "v" from Tag
        id: set-tag
        run: echo "CLEAN_TAG=${GITHUB_EVENT_RELEASE_TAG_NAME#v}" >> $GITHUB_OUTPUT
        env:
          GITHUB_EVENT_RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

  Publish:
    runs-on: ubuntu-latest
    needs: ['Test','Strip_Version']
    steps:
      - name: Create Directory
        run: mkdir -p ./lib

      - name: Download the build artifact
        uses: actions/download-artifact@v4
        with:
          name: cache
          path: ./

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org/'

      - name: Update Version in Package.json
        id: set-npm-tag
        run: | 
         npm version ${{ steps.set-tag.outputs.clean_tag }} --no-git-tag-version
         if [[ "${{ steps.set-tag.outputs.clean_tag }}" == *"beta"* ]]; then
           echo "NPM_TAG=beta" >> $GITHUB_OUTPUT
         else
           echo "NPM_TAG=latest" >> $GITHUB_OUTPUT
         fi

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
          tag: ${{ steps.set-npm-tag.outputs.npm_tag }}

  Update_Repo:
    runs-on: ubuntu-latest
    needs: ['Test','Strip_Version']
    steps:
      - uses: actions/checkout@v4

      - name: Update Version in Package.json
        run: npm version ${{ steps.set-tag.outputs.clean_tag }} --no-git-tag-version

      - name: Update Version in Package.json
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_message: "chore(release): update to version ${{ github.event.release.tag_name }}"
          force: false

  Document:
    needs: Publish
    uses: ./.github/workflows/action-docs.yaml

