name: Release and Publish
on:
  release:
    types:
      - published

permissions:
  contents: write
  actions: write
  checks: write

jobs:
  Test:
    uses: ./.github/workflows/action-test.yaml

  Strip_Version:
    runs-on: ubuntu-latest
    steps:
      - name: Strip "v" from Tag
        run: |
          echo "CLEAN_TAG=${GITHUB_EVENT_RELEASE_TAG_NAME#v}" >> $GITHUB_ENV
        env:
          GITHUB_EVENT_RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

  Publish:
    runs-on: ubuntu-latest
    needs: ['Test','Strip_Version']
    steps:
      - name: Create Directory
        run: mkdir -p ./lib

      - name: Download the build artifact
        uses: actions/download-artifact@v4
        with:
          name: cache
          path: ./

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org/'

      - name: Update Version in Package.json
        run: |
          npm version $CLEAN_TAG --no-git-tag-version

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
          tag: |
            if [[ "$CLEAN_TAG" == *"beta"* ]]; then
              beta
            else
              latest
            fi

  Update_Repo:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: actions/checkout@v4

      - name: Update Version in Package.json
        run: npm version $CLEAN_TAG --no-git-tag-version

      - name: Update Version in Package.json
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_message: "chore(release): update to version $CLEAN_TAG"
          force: false

#      - name: Update Version in Package.json
#        run: |
#          npm version $CLEAN_TAG --no-git-tag-version
#          git config user.name "github-actions[bot]"
#          git config user.email "github-actions[bot]@users.noreply.github.com"
#          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
#          git commit -am "chore(release): update to version $CLEAN_TAG"
#          git pull
#          git push origin HEAD:main
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  Document:
    needs: Publish
    uses: ./.github/workflows/action-docs.yaml

