name: Release and Publish
on:
  release:
    types:
      - published

permissions:
  contents: write
  actions: write
  checks: write

jobs:
  Test:
    uses: ./.github/workflows/action-test.yaml

  Change_Log:
    needs: Test
    uses: ./.github/workflows/update-changelog.yaml

  Publish:
    needs: ['Change_Log', 'Test']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: 'false'

      - name: Create Directory
        run: mkdir -p ./lib

      - name: Download the build artifact
        uses: actions/download-artifact@v4
        with:
          name: cache
          path: ./

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org/'

      - name: Strip "v" from Tag
        run: echo "CLEAN_TAG=${GITHUB_EVENT_RELEASE_TAG_NAME#v}" >> $GITHUB_ENV
        env:
          GITHUB_EVENT_RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Update Version in Package.json
        run: |
          npm version $CLEAN_TAG --no-git-tag-version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore(release): update to version $CLEAN_TAG"

      - name: Push to Repo
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            git push origin develop
          else
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            # npm publish --tag beta
            echo NPM Publish (Beta)
          else
            # npm publish
            echo NPM Publish (Real Version)
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  Document:
    needs: Publish
    uses: ./.github/workflows/action-docs.yaml

