name: Release Drafter

on:
  push:
    branches:
      - main
      - develop

jobs:
  update_release_draft:
    name: Release Drafter
    runs-on: ubuntu-latest

    steps:
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
