name: Release Drafter

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  update_release_draft:
    name: Release Drafter
    runs-on: ubuntu-latest

    steps:

      - name: Update Release Draft (Develop)
        if: github.event.pull_request.base.ref == 'develop'
        uses: release-drafter/release-drafter@v6
        with:
          prerelease: true
          commitish: develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release Draft
        if: github.ref == 'refs/heads/main'
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}